updated deployment workflow

diff --git a/.github/workflows/eslintcheck.yaml b/.github/workflows/eslintcheck.yaml
--- a/.github/workflows/eslintcheck.yaml
+++ b/.github/workflows/eslintcheck.yaml
@@ -32,6 +32,11 @@ jobs:
         continue-on-error: true
         id: eslint
 
+      - name: Run security audit
+        run: npm audit
+        continue-on-error: true
+        id: security-audit
+
       - name: block PR if ESLint fails
         continue-on-error: true
         if: steps.eslint.outcome == 'failure'
@@ -47,17 +52,6 @@ jobs:
               body: 'ESLint check failed. Please fix all linting issues (including warnings) before merging.'
             })
 
-      - name: Run security audit
-        run: npm audit
-        continue-on-error: true
-        id: security-audit
-
-      - name: check for ESLint result
-        if: steps.eslint.outcome == 'failure'
-        run: |
-          echo "ESLint found issues. Failing the workflow."
-          exit 1
-      
       - name: block PR if Security Check fails
         continue-on-error: true
         if: steps.security-audit.outcome == 'failure'
@@ -72,6 +66,18 @@ jobs:
               event: 'REQUEST_CHANGES',
               body: 'Security check failed. Please fix all security warnings issues (including warnings) before merging.'
             })
+
+      - name: check for ESLint result
+        if: steps.eslint.outcome == 'failure'
+        run: |
+          echo "ESLint found issues. Failing the workflow."
+          exit 1
+
+      - name: check for Security result
+        if: steps.security-audit.outcome == 'failure'
+        run: |
+          echo "Security Check issues found. Failing the workflow."
+          exit 1
 
       - name: build Project from React Files
         run: npm run build
