added security check in workflow

diff --git a/.github/workflows/eslintcheck.yaml b/.github/workflows/eslintcheck.yaml
--- a/.github/workflows/eslintcheck.yaml
+++ b/.github/workflows/eslintcheck.yaml
@@ -18,14 +18,26 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
+      - name: setup NodeJS for Build
+        uses: actions/setup-node@v4
         with:
-          node-version: '20'
+          node-version: 20
+          cache: "npm"
 
-      - name: install all the dependencies
-        run: npm install
+      - name: install all Dependencies
+        run: npm ci
+        
+      - name: Run security audit
+        run: npm audit
+        continue-on-error: true
+        id: security-audit
 
+      - name: Check for security vulnerabilities
+        if: steps.security-audit.outcome == 'failure'
+        run: |
+          echo "Security vulnerabilities found. Failing the workflow."
+          exit 1
+      
       - name: Run ESLint test
         run: npm run lint:strict
         continue-on-error: true
@@ -36,7 +48,7 @@ jobs:
         if: steps.eslint.outcome == 'failure'
         uses: actions/github-script@v6
         with:
-          github-token: ${{ secrets.VAI }}
+          github-token: ${{ github.tokens }}
           script: |
             github.rest.pulls.createReview({
               owner: context.repo.owner,
@@ -51,15 +63,6 @@ jobs:
         run: |
           echo "ESLint found issues. Failing the workflow."
           exit 1
-          
-      - name: setup NodeJS for Build
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: "npm"
-
-      - name: install all Dependencies
-        run: npm ci
 
       - name: build Project from React Files
         run: npm run build
@@ -70,7 +73,7 @@ jobs:
       - name: deploy to netlify
         continue-on-error: true
         id: netlify-deploy
-        uses: nwtgck/actions-netlify@v2.0
+        uses: nwtgck/actions-netlify@v3.0
         with:
           publish-dir: './build'
           production-branch: main
@@ -78,8 +81,7 @@ jobs:
           deploy-message: "FROM GITHUB_ACTIONS"
           enable-pull-request-comment: true
           enable-commit-comment: false
-          overwrites-pull-request-comment: true
-          enable-github-deployment: false
+          overwrites-pull-request-comment: false
           alias: healthcare-deploy-preview-${{ github.event.number }}
         env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
